#!/usr/bin/env bash
# =============================================================================
# Installer for Plex Auto-Updater
# Run as root: sudo bash install-plex-updater.sh
# =============================================================================

set -euo pipefail

INSTALL_DIR="/opt/plex-autoupdate"
CONFIG_FILE="/etc/plex-autoupdate.conf"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Plex Auto-Updater Installer ==="
echo ""

# Check root
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This installer must be run as root (use sudo)."
    exit 1
fi

# Check dependencies
echo "Checking dependencies..."
for cmd in curl python3 dpkg systemctl; do
    if ! command -v "$cmd" &>/dev/null; then
        echo "  ERROR: '$cmd' is required but not found."
        exit 1
    fi
    echo "  OK: $cmd"
done
echo ""

# ---------------------------------------------------------------------------
# Interactive setup
# ---------------------------------------------------------------------------

# Plex Token
echo "--- Plex Token ---"
read -rp "Enter your Plex authentication token: " USER_PLEX_TOKEN
if [[ -z "$USER_PLEX_TOKEN" ]]; then
    echo "WARNING: No token provided. You'll need to set it manually in $CONFIG_FILE"
    USER_PLEX_TOKEN="YOUR_PLEX_TOKEN_HERE"
fi
echo ""

# Update channel
echo "--- Update Channel ---"
echo "  1) public    - Stable releases (recommended for most users)"
echo "  2) plexpass  - Beta builds (requires Plex Pass subscription)"
read -rp "Select channel [1/2] (default: 1): " CHANNEL_CHOICE
case "$CHANNEL_CHOICE" in
    2|plexpass) USER_CHANNEL="plexpass" ;;
    *)          USER_CHANNEL="public" ;;
esac
echo "  Selected: $USER_CHANNEL"
echo ""

# Email notifications
echo "--- Email Notifications ---"
read -rp "Enable email notifications? [y/N]: " EMAIL_CHOICE
EMAIL_CHOICE=$(echo "$EMAIL_CHOICE" | tr '[:upper:]' '[:lower:]')
USER_EMAIL_ENABLED="no"
USER_EMAIL_TO=""

if [[ "$EMAIL_CHOICE" == "y" || "$EMAIL_CHOICE" == "yes" ]]; then
    USER_EMAIL_ENABLED="yes"
    read -rp "Email address for notifications: " USER_EMAIL_TO
    if [[ -z "$USER_EMAIL_TO" ]]; then
        echo "WARNING: No email provided. Disabling email notifications."
        USER_EMAIL_ENABLED="no"
    fi

    # Check for mail command
    if command -v mail &>/dev/null; then
        echo "  OK: mail command found"
    elif command -v sendmail &>/dev/null; then
        echo "  OK: sendmail command found"
    else
        echo "  WARNING: No mail command found. Install mailutils for email to work:"
        echo "           apt install mailutils"
    fi
else
    echo "  Email notifications disabled."
fi
echo ""

# Max wait time
echo "--- Wait Timeout ---"
echo "  How long to wait (in minutes) for active streams to finish"
echo "  before giving up. (Default: 360 = 6 hours)"
read -rp "Max wait minutes [360]: " USER_MAX_WAIT
USER_MAX_WAIT=${USER_MAX_WAIT:-360}
# Validate it's a number
if ! [[ "$USER_MAX_WAIT" =~ ^[0-9]+$ ]]; then
    echo "  Invalid number. Using default: 360"
    USER_MAX_WAIT=360
fi
echo "  Set to: $USER_MAX_WAIT minutes"
echo ""

# ---------------------------------------------------------------------------
# Install script
# ---------------------------------------------------------------------------
echo "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
cp "$SCRIPT_DIR/plex-autoupdate.sh" "$INSTALL_DIR/plex-autoupdate.sh"
chmod 755 "$INSTALL_DIR/plex-autoupdate.sh"
echo "  OK: Script installed"

# ---------------------------------------------------------------------------
# Generate config
# ---------------------------------------------------------------------------
if [[ -f "$CONFIG_FILE" ]]; then
    echo "  WARNING: Config already exists at $CONFIG_FILE"
    read -rp "  Overwrite? [y/N]: " OVERWRITE
    OVERWRITE=$(echo "$OVERWRITE" | tr '[:upper:]' '[:lower:]')
    if [[ "$OVERWRITE" != "y" && "$OVERWRITE" != "yes" ]]; then
        echo "  Keeping existing config. New template saved to ${CONFIG_FILE}.new"
        cp "$SCRIPT_DIR/plex-autoupdate.conf" "${CONFIG_FILE}.new"
    else
        WRITE_CONFIG="yes"
    fi
else
    WRITE_CONFIG="yes"
fi

if [[ "${WRITE_CONFIG:-}" == "yes" ]]; then
    cat > "$CONFIG_FILE" << CONF
# =============================================================================
# Plex Auto-Updater Configuration
# Generated by installer on $(date '+%Y-%m-%d %H:%M:%S')
# =============================================================================

PLEX_TOKEN="$USER_PLEX_TOKEN"
PLEX_URL="http://localhost:32400"

# Update channel: "plexpass" (beta) or "public" (stable)
UPDATE_CHANNEL="$USER_CHANNEL"

# Max wait time for active streams (minutes)
MAX_WAIT_MINUTES=$USER_MAX_WAIT

# Session check interval (seconds)
CHECK_INTERVAL_SECONDS=120

# Email notifications
EMAIL_ENABLED="$USER_EMAIL_ENABLED"
EMAIL_TO="$USER_EMAIL_TO"
EMAIL_FROM="plex-updater@$(hostname -f 2>/dev/null || echo 'localhost')"
EMAIL_SUBJECT_PREFIX="[Plex Updater]"

# Paths
LOG_FILE="/var/log/plex-autoupdate.log"
DOWNLOAD_DIR="/tmp/plex-update"
CONF
    chmod 600 "$CONFIG_FILE"  # Protect the token
    echo "  OK: Config written to $CONFIG_FILE"
fi

# Create log file
touch /var/log/plex-autoupdate.log
chmod 644 /var/log/plex-autoupdate.log
echo "  OK: Log file created"

echo ""

# ---------------------------------------------------------------------------
# Set up cron
# ---------------------------------------------------------------------------
echo "Setting up cron job..."
CRON_LINE="0 */6 * * * ${INSTALL_DIR}/plex-autoupdate.sh >> /var/log/plex-autoupdate.log 2>&1"

if crontab -l 2>/dev/null | grep -q "plex-autoupdate"; then
    echo "  WARNING: Cron job already exists. Skipping."
else
    (crontab -l 2>/dev/null || true; echo "$CRON_LINE") | crontab -
    echo "  OK: Cron job added (runs every 6 hours)"
fi

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Summary:"
echo "  Channel:       $USER_CHANNEL"
echo "  Email:         ${USER_EMAIL_ENABLED} ${USER_EMAIL_TO:+($USER_EMAIL_TO)}"
echo "  Max wait:      ${USER_MAX_WAIT} minutes"
echo "  Config:        $CONFIG_FILE"
echo "  Script:        ${INSTALL_DIR}/plex-autoupdate.sh"
echo "  Logs:          /var/log/plex-autoupdate.log"
echo "  Cron:          every 6 hours (edit with 'crontab -e')"
echo ""
echo "To test now:  ${INSTALL_DIR}/plex-autoupdate.sh"
echo "To reconfigure: edit $CONFIG_FILE"